### ISSUE TITLE
Reset MSL and Timer Position

### ISSUE THREAD

**Issue by aturneruk** [VATSIM-UK/uk-controller-plugin#103]
I often switch between screens for my Euroscope between my laptop screen and an external monitor. Due to the different resolutions/scaling between these displays, my timer and MSL boxes when positioned on the external monitor (on the far right hand side) aren't visible on the laptop screen. 

Whilst I can fix this by restarting ES and editing the .prf file, it would be very useful if the positions of the MSL and timer boxes could be reset, either using a dedicated option or simply when their visibility are toggled using the existing options. 

Thank you!

**Comment by AndyTWF** [comment]
Hi Adam!

Thanks for raising this. We already have a command ‘.ukcp resetvisuals’ for this! I appreciate that’s not well documented so I’ll look at adding it to the menu / adding a command guide to the plugin :)

Thanks!

**Comment by hsugden** [comment]
Could perhaps be closed now, with the link to the Help in the OP menu?

**Comment by AndyTWF** [comment]
Yep!
