### ISSUE TITLE
Aircraft Removal from Holding List

### ISSUE THREAD

**Issue by nikki2048** [VATSIM-UK/uk-controller-plugin#110]
Hello,
would it be possible to allow for aircraft removal directly from the holding manager / list? This could be done by simply right-clicking on the aircraft which is currently displayed within the hold.

Thank you!

**Comment by AndyTWF** [comment]
Hi @nikki2048, in the upcoming version of hold manager, I have made it possible to change / remove the hold by click on the aircrafts callsign in the hold display :)
