### ISSUE TITLE
LESLU Intention Code Not Displayed

### ISSUE THREAD

**Issue by luke11brown** [VATSIM-UK/uk-controller-plugin#111]
Route was:
IDRID M40 SABER L980 LAM L179 UGBET/N0476F340 Q60 UGNUS L18 DIKAS L180 LESLU/M084F340 DCT SOMAX NATA ELSIR N324A MIILS/N0487F340 DCT LETAK IMEBA5

**Comment by luke11brown** [comment]
Fixed it by putting a space after LESLU

**Comment by AndyTWF** [comment]
Thanks for the report! I'll have a look into this!
