### ISSUE TITLE
Improve VSL

### ISSUE THREAD

**Issue by cbyworth** [VATSIM-UK/uk-controller-plugin#120]
Improvements to VSL:
- Automatically add arriving aircraft to VSL for terminal holds - based off intention code and stack (eg. For LAM and LL and WU intention codes) - aircraft added once within designated "capture area" for each stack (eg 15 nm of fix)
- Add button will allow manual addition of aircraft that may be relevant to the stack, ideally flagged in alternative colour
- Aircraft passing through the stack area at a conflicting level (ie at the same level as a stack aircraft) should automatically be inserted into the VSL
- Aircraft subject to STCA should be highlighted in VSL (if it's possible to identify STCA from euroscope?)
- For enroute holds we should probably stick with manual addition?

![Screenshot_20200410-213035](https://user-images.githubusercontent.com/45854780/79023534-73f5c500-7b78-11ea-923c-ae6880d5ab92.png)

Related Issue #78

**Comment by cbyworth** [comment]
What I don't know is whether the 'Same Level Indicator' only activates on stack aircraft (eg LL/WU for LAM) and non-stack aircraft are only for e inserted if STCA activates, or if non-stack aircraft are force inserted whenever they enter the defined region.

**Comment by AndyTWF** [comment]
This now implemented in the new VSL - please open a new issue if there's anything else to add :)
