### ISSUE TITLE
Override hold levels

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-plugin#125]
It would be useful to be able to override the holding level limits in the API. Obviously on VATSIM we don't always stick to the rules...

I was holding up to FL200 in ROSUN and MIRSI today 😄

**Comment by AndyTWF** [comment]
Hi @hsugden, the latest version of hold manager will default to any hold published at the requested fix, but will allow you to override it anywhere between 1000 and FL660 :)
