### ISSUE TITLE
Adjusting assigned altitudes in hold manager

### ISSUE THREAD

**Issue by luketp** [VATSIM-UK/uk-controller-plugin#131]
Would it be possible to make the cleared flight level modifiable in the hold manager (same as on the main aircraft tags)?

Idea would be to make it easier to select the right aircraft and change their CFL when they're all in a stack together.

**Comment by AndyTWF** [comment]
Hi @luketp , just to confirm this has been implemented and will go out when the next version of UKCP's hold manager ships :)
