### ISSUE TITLE
IVV Tag Item

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/uk-controller-plugin#132]
- Detect if aircraft gets airborne from controlled airport, if right code do nothing.
- Show some notification on departure if departed from uncontrolled / aerodrome doesn't have the automatic IVV "procedure" in place. Same if code not matching UKCP.
- Controller to click TAG item to confirm IVV.

**Comment by hsugden** [comment]
Will this rely on Easy VATSIM mode?

**Comment by hsugden** [comment]
@AndyTWF no longer required. Issue can be closed 🔐
