### ISSUE TITLE
SRD copy route string

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-plugin#143]
Copying route string should also copy end point

e.g. search for EGKK -> REDFA, copy the last route, and it gives me:

FRANE M604 GASBA M197

when I would really like:

FRANE M604 GASBA M197 REDFA

**Comment by AndyTWF** [comment]
Hi @hsugden this has been fixed in the API at https://github.com/VATSIM-UK/uk-controller-api/pull/168 :)
