### ISSUE TITLE
Ability to change font size in the Hold Manager

### ISSUE THREAD

**Issue by louielister** [VATSIM-UK/uk-controller-plugin#147]
The new font that controllers use for their EuroScope clashes with the Hold Manager meaning that callsigns are dropping into other lines. The ability to change font size or enlarge the Hold Manager box would be awesome. Example [here](https://prnt.sc/sxfuf9).

**Comment by AndyTWF** [comment]
Hi @louielister - is this still an issue with the new Hold Manager?

**Comment by louielister** [comment]
Hi, I feel like this was fixed but I can't actually remember. I'll try it again in next weeks event.

**Comment by luke11brown** [comment]
This seems to no longer be an issue with the new style VSL

**Comment by AndyTWF** [comment]
Closing as fixed with new VSL.
