### ISSUE TITLE
Next Controller Not Populating

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/uk-controller-plugin#148]
E.g. https://prnt.sc/sy314h

**Comment by TheoBearman** [comment]
Can confirm this issue in live. LON_S_CTR not populating GOGSI departures when online:

![image](https://user-images.githubusercontent.com/6546590/85222487-48caf580-b3b3-11ea-9c5b-7bade1a0701c.jpeg)

**Comment by AndyTWF** [comment]
Thanks for the confirm @TheoBearman - found the issue so will fix asap.

**Comment by AndyTWF** [comment]
Fixed in https://github.com/VATSIM-UK/uk-controller-api/pull/174
