### ISSUE TITLE
Implement TopSky Style Planning Graphics

### ISSUE THREAD

**Issue by TheoBearman** [VATSIM-UK/uk-controller-plugin#150]
As discussed on Slack, it would be great if we could have some dynamic planning graphics implemented in UKCP. Implementations of these would certainly be relevant at an aerodrome, radar and AC-wide level.

An example screenshot is below.

Thanks in advance!

![Image of TopSky implementation](https://scontent-lhr8-1.xx.fbcdn.net/v/t1.0-9/83146456_3535788209769262_7883195365592904031_n.jpg?_nc_cat=102&_nc_sid=110474&_nc_ohc=7lwN6E9k0Z8AX928nI3&_nc_ht=scontent-lhr8-1.xx&oh=6a5afcf2e30278f9bb7c8ceae02fb526&oe=5F0BC2DC)

**Comment by hsugden** [comment]
Think this can be closed - I will just advocate for the use of TopSky when coordinating
