### ISSUE TITLE
QFE info

### ISSUE THREAD

**Issue by codelyokop** [VATSIM-UK/uk-controller-plugin#156]
Small pannel that gives the QFE for an airport based from the airport elevation and the metar. Fetch latest metar then from a db of airport elevations do the QFE calculation so controllers have a visual QFE indication. Benifits military the most alongside circuit traffic

**Comment by PLM1995** [comment]
I love the idea of a QFE display, but a database of field elevations seems unnecessarily complicated. At most you could have a database of QFE offsets, but as a first pass I think a simple setting where you can choose an offset (which gets saved per ASR) would be great!
