### ISSUE TITLE
Remove Initial Altitude On Departure If No Onward ATC

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/uk-controller-plugin#16]
When an aircraft departs, they should not depart with an initial altitude set if no receiving ATC is online

**Comment by hsugden** [comment]
Love this!

**Comment by codelyokop** [comment]
Good idea however what if Onward ATC then comes online. its already comon knowledge that if there is no further then you can climb and descend as you feel like.

**Comment by hsugden** [comment]
I'm not quite sure I understand what you're saying @codelyokop 

The idea of this is simply to remove the initial climb set on an aircraft's tag in EuroScope when there is no APP/CTR online. It has nothing to do with what the pilot sees? It's to remove the hassle of having an aircraft at FL290 as EBBU_CTR with an initial climb of A40 still set.

**Comment by codelyokop** [comment]
@hsugden I see your point. I've been viewing it from the side of the PDC. If vSMR is used then it takes that CFL as the initial climb. I'm unsure how the alias is quite set up to know if it would be affected for those doing PDC through PM. I know those using topsky don't get the issue as then each PDC message is pre-setup in the topsky configs. Il have a look into the alias file tonight. Where my main division in vACC Swiss is the clearance line with initial climb is manually entered.

**Comment by hsugden** [comment]
Not _depart_ with it set. I think the idea would be to clear it on departure if no onward ATC. It would still be set while the aircraft is on the ground and thus not affect PDC/clearance or whatever

**Comment by codelyokop** [comment]
Yeah that would be a good way to implement it
