### ISSUE TITLE
Notification System

### ISSUE THREAD

**Issue by cbyworth** [VATSIM-UK/uk-controller-plugin#160]
Would provide a notification of ATC Procedure Change whenever a post is made in the relevant forum or a new vMATS is released. 
Callsign specific when connecting to the network but should probably include top down positions or adjacent positions that are affected.
Would provide a link to the forum post.
Would include both permanent and temporary procedures.

Example - LTC_M_CTR opened for event.
EGNX_APP connects, hasn't recently checked the forum, notification generated flagging a procedure change because TC Midlands is open.

**Comment by hsugden** [comment]
Wow, I wrote a [spec for a Procedure Change Notification System](https://docs.google.com/document/d/1G_hm_Z0rKObXPDwOUz_kH4yhH28udHIhG1HdBbopUdE/edit) maybe a year ago and updated it a couple of days after you opened this issue @cbyworth! 😮 

And look what a member of the Web Team's response included:

![image](https://user-images.githubusercontent.com/12017284/91540754-2a352d80-e913-11ea-8093-2f36125aaadb.png)

Mind reading...

In all seriousness, I like the idea, but am still unsure as to how much work it would be compared to a wider review of how controllers are kept up to date with procedure changes? Would the suggestion as per this issue be able to develop in future into something that allows our trainees to know how to keep up to date _in advance_ of controlling, for example. Anyway, an interesting discussion!

**Comment by CalumTowers** [comment]
We are exploring the idea of a notification system for UKCP as an MVP for this. We'll use the system to channel procedure change notifications that are relevant to the person logging in. I think this will solve the immediate need and we can look at how we build on that in the future.

**Comment by hsugden** [comment]
Another use case found for this system:

https://community.vatsim.uk/topic/37582-2020-12-27-temporary-instruction-routing-restrictions-to-dublin-tma/
https://community.vatsim.uk/topic/37447-2020-11-14-temporary-instruction-dublin-flow-control/

To notify controllers of relevant temporary instructions, where they pertain to routing restrictions, flow control, coordination, etc.

**Comment by CalumTowers** [comment]
> Another use case found for this system:
> 
> https://community.vatsim.uk/topic/37582-2020-12-27-temporary-instruction-routing-restrictions-to-dublin-tma/
> https://community.vatsim.uk/topic/37447-2020-11-14-temporary-instruction-dublin-flow-control/
> 
> To notify controllers of relevant temporary instructions, where they pertain to routing restrictions, flow control, coordination, etc.

There is far too much mind-reading going on within this issue. @AndyTWF, @AxonC and I have been talking about administative functionality for members of the Ops Team to be able to update SIDs/initial altitudes etc each cycle and I was also thinking about how such an admin tool would then open a nice path to get this feature implemented too.

**Comment by hsugden** [comment]
Completed? Only thing I guess would be an interface, and more advanced filtering of notifications - e.g. if a notification is for EGKK_TWR, then any controller covering that position top-down would also see the notification without having to define all the options

**Comment by AndyTWF** [comment]
The MVP has been implemented - please open a new issue for future ideas :)
