### ISSUE TITLE
Initial Altitudes Reset If Cleared

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/uk-controller-plugin#166]
If an initial altitude is cleared (in Euroscope, set to 0 by the controller), it gets reset whenever the FP is changed.

Edit: May also occur if changing to cruise or typing?

**Comment by hsugden** [comment]
Notably seems to happen when aircraft are airborne - only think initial altitudes are worth bothering to think about setting on the ground? Unless there might be another occasion you can think of?
