### ISSUE TITLE
Ability to set longer timers

### ISSUE THREAD

**Issue by aeroniemi** [VATSIM-UK/uk-controller-plugin#167]
It'd be really handy to be able to set timers longer than 15 mins (eg 20, 30 mins) as part of the ES timerboard for things like oceanic, MDI/release expiry, etc. Can currently set times up to 999 seconds, (which is like 17 mins)

**Comment by AndyTWF** [comment]
Hi @aeroniemi - I've added the ability to increase up to 3600s (1 hour) and it'll go out in the next UKCP release :) In the future I may look to handling minutes, seconds etc so it looks a bit nicer - but hopefully this is a starting point whilst I look into it.

**Comment by aeroniemi** [comment]
Brill! tbh, that's probably enough to make the few people that actually care about this happy (inc me!)
