### ISSUE TITLE
Local squawk allocated for domestic FP in EGJJ

### ISSUE THREAD

**Issue by jamlen** [VATSIM-UK/uk-controller-plugin#170]
For EGJJ and squawk allocation, if an aircraft is flying to EGBB the plugin plugin allocate 1201-1277 (as in the vMATs). I've just had it allocate 3630 which is marked as Inter-island

![uk-controller-plugin-squawk-allocation](https://user-images.githubusercontent.com/3593671/91103623-dbae3780-e663-11ea-8d9a-8718693b98aa.PNG)

**Comment by AndyTWF** [comment]
Hi @jamlen,

Thanks for the report. Probably a randomisation of which squawk range gets picked somewhere (it uses a random range within all the possibles to allocate from), I will have a look!

**Comment by AndyTWF** [comment]
Hi again @jamlen - I've had a look at the squawk assignment history on our API and can see no trace of those squawks being assigned to those aircraft.

I was thinking, do you have the "Auto Assign Squawks" option turned on in EuroScope? I believe it's in the General Settings menu. If you do, that possibly may have caused it?

**Comment by jamlen** [comment]
@AndyTWF for context, the aircraft had arrived and refiled so I did the right-click "Auto Assign" option. I can't find a setting in the General Settings for "Auto Assign Squawks" - here are my settings.

![uk-controller-plugin-squawk-allocation-02](https://user-images.githubusercontent.com/3593671/91214745-7281ff00-e70b-11ea-9364-f03c9a92bb32.PNG)

And these are the UKCP settings:

![uk-controller-plugin-squawk-allocation-03](https://user-images.githubusercontent.com/3593671/91214863-99d8cc00-e70b-11ea-8913-e198e1bcdeb3.PNG)

**Comment by AndyTWF** [comment]
Hi James, If you clicked "Auto Assign" in a menu (next to the option for manually setting a squawk in the little green menu that pops up), that's the EuroScope inbuilt squawk generation, rather than UKCP's.

ES generates its squawks based on the Squawk options of the general settings menu, the range of which changes depends on where you logged on. For JJTWR, that range is 3601 vs 3647.

To use the UKCP squawk generation, you can assign the TAG function for force recycling squawks (General, as opposed to Local) :)

**Comment by jamlen** [comment]
Ahh OK, so how do I assign the TAG function as you suggest?

**Comment by AndyTWF** [comment]
In the departure list, click the little "S" to open up the column setup. For the column that you want to use the function on, use the Left button/Right button menus to select a function - all of the UKCP ones are at the bottom and are preceded with "UK Controller Plugin".

The one you want for this case is "Force Squawk Recycle (General)" - this will assign a random squawk based on where the aircraft is flying etc.

The "local" version is slightly different - it asks the plugin to assign one of the discrete codes assigned to Jersey APP.
