### ISSUE TITLE
Temporary altitude change upon amending flight plan

### ISSUE THREAD

**Issue by kusterjs** [VATSIM-UK/uk-controller-plugin#177]
I've lately observed lots of aircraft coming from UK airspace and flying into Switzerland get their temporary altitude changed upon amending the flight plan for the first time. It's just a wild guess, but as this has happened in the past, I urgently ask you to check that no temporary altitude change commands (looks like the initial climb clearance for the departure airport) are created by the plugin when the aircraft is not visible to the controller.
I've a number of logs where you can see EG** stations settings altitudes of 4000, 5000 or 6000 for aircraft just at the boundary to LSAS airspace.

**Comment by becas22** [comment]
Same happens with Portugal.

**Comment by AndyTWF** [comment]
Hi @kusterjs and @becas22,

Thanks for the report.

This should not be possible with UKCP as the plugin only assigns initial altitudes in the air of the aircraft is tracked by the user. On the ground it only does it for aircraft within a very small distance of the origin.

It’s possible that controllers may still have VCA switched on as well (I believe it works again now after it stopped for a while) so that may be doing it as I don’t believe the bug was ever fixed.

Of course, I shall double check the code (it’s not changed for a few years now) to be sure.

**Comment by kusterjs** [comment]
Was the altitude also set by other controllers in VCA? Because I can observe this behaviour from the log files.

I shall check the actual controllers then and ask them if they used VCA.

**Comment by AndyTWF** [comment]
I’m just aware that a few of the very old controller packs out there contain VCA, so maybe some people are using it by accident! Any further information you can get will be very welcome!

**Comment by kusterjs** [comment]
Any chance you can inform UK controllers to not use any old VCA plugin please?

**Comment by AndyTWF** [comment]
@kusterjs the UK have advised against VCA since UKCP came out :)

**Comment by AndyTWF** [comment]
For context, these are the rules UKCP uses for assigning initial altitudes: https://github.com/VATSIM-UK/uk-controller-plugin/blob/75a4810d0becae268c59390509e3952699ec9f5f/src/initialaltitude/InitialAltitudeEventHandler.cpp#L175

From the code, to assign an initial altitude automatically, the aircraft must meet all of these conditions:

```
        /*
            Returns true if the aircraft meets the prerequisites for initial altitude assignment.
            To return true, must:
            1. Be within a specified distance of the origin airport.
            2. Be under a certain speed.
            3. Not have a cleared altitude set.
            4. Not be tracked by any controller.
            5. Not be "simulated" by ES.
            6. Have a user that has a recognised callsign.
            7. Have the airfield of origin owned by the controller.
        */
```

Of course, a controller could force an update by clicking a TAG item on an aircraft, but I'd find that quite unlikely so far south as nobody's vis range goes that far!

**Comment by hsugden** [comment]
Think this can be closed?

**Comment by AndyTWF** [comment]
Yes - this can now be closed as the issue was (eventually) found and resolved :)
