### ISSUE TITLE
Countdowm & Holds list bars disappeared

### ISSUE THREAD

**Issue by DevonFly** [VATSIM-UK/uk-controller-plugin#180]
Hello

After installing the UK Controller Pack plugin, the Countdown, MSL & Holds list bars always appeared near the top left of the screen.

Recently, I re-installed the plugin v 2.5.2 and the MSL list bar was at the top, but the other 2 were just showing above the flight card bar at the foot of the screen. I was unable to click on them to pull them up the screen.

The next time I logged on, the Countdown & Holds list bars had completely disappeared and have not returned. The MSL had also disappeared, but can be re-instated and shows at the top of the screen by opening its configuration and ticking to display it. The other 2 do not operate like that; the configuaration & display options do not re-display them on screen and I have been unable to recover them.

I have read just about every .txt type file in Euroscope but cannot find anything that would enable me to reset them. I have also tried unloading the plugin, logging out then logging back in and loading the plugin without success.

Any ideas on how I can recover these list bars and content please ?
[RM OP Hold-Count elements lost 24-11-2020.pdf](https://github.com/VATSIM-UK/uk-controller-plugin/files/5591320/RM.OP.Hold-Count.elements.lost.24-11-2020.pdf)

**Comment by AndyTWF** [comment]
Hi @DevonFly,

You should be able to find the positions set in your .asr files in ES.

If you'd prefer to try the nuclear option, you can use the command `.ukcp resetvisuals` which will force everything back to 100,100 :)

**Comment by DevonFly** [comment]
Thanks very much Andy
The countdown had gone to x - 1512 !
I now have recovered the Countdown, but even with the nuclear option, the Holds bar has not re-appeared. I notice that there is no X & y location setting for this in any .asr

**Comment by AndyTWF** [comment]
With the reset visuals command, any holds you've got displayed should have defaulted to 100,100 too - have you got any holds configured to display at the moment (Display Managed Holds ticked plus selected holds chosen)?

**Comment by DevonFly** [comment]
I did not have. I attach screen showing result of ticking Display Managed Holds and then configuring holds Willo & Timba.
I thought that before I lost it, a small list showing the relevant (ie Gatwick for example) holds appeared with the MSL & Countdown. It is that small window that does not appear to have come back
[RM OP ukcp options recovered 25-11-2020.pdf](https://github.com/VATSIM-UK/uk-controller-plugin/files/5597720/RM.OP.ukcp.options.recovered.25-11-2020.pdf)

**Comment by AndyTWF** [comment]
UKCP doesn't have any functionality that displays "relevant" holds (yet!) - but what you've shown in that screenshot looks like everything working properly!

**Comment by DevonFly** [comment]
Thanks very much Andy. You have been very helpful. Have a merry Christmas !

**Comment by AndyTWF** [comment]
You're most welcome, and to yourself :) I'll close this one now but feel free to re-open or raise another issue if needed!
