### ISSUE TITLE
vStrips and vSMR Stand Integration

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/uk-controller-plugin#184]
- Provide a way for vStrips to detect whether UKCP is running.
- Provide a way for vStrips/vSMR to modify the assigned stands.

**Comment by chssn** [comment]
@AndyTWF vStrips already appears to modify assigned stands in EuroScope. In the example below, I have selected stand 153 at Gatwick in vStrips for AFR1010 and it has then updated the SPad column with the same stand.

![image](https://user-images.githubusercontent.com/33300267/102514202-1b21e900-4084-11eb-9182-d0a42e6e2808.png)

![image](https://user-images.githubusercontent.com/33300267/102514327-3db40200-4084-11eb-8f5d-61f9a470b24b.png)

EuroScope v3.2.1.25 (running local sweatbox simulation)
vStrips v1.14.0.0
vStripsESP v1.18 (EuroScope plugin)
UK Controller Plugin v2.5.2
vSMR v1.5.117

**Comment by AndyTWF** [comment]
That's not UKCPs stand items, that's vStrips own version of :)
