### ISSUE TITLE
Stands issued with aircraft on stand

### ISSUE THREAD

**Issue by trevorhannant** [VATSIM-UK/uk-controller-plugin#187]
At EGGD, LON_W with no underlying coverage (if it makes any difference...).

16:47 - EZY978 connects on Stand 1
EZY296 was subsequently assigned stand 1:

![stands](https://user-images.githubusercontent.com/24749537/102726184-6e11cf80-4314-11eb-860d-c9f935eca7f3.png)

From the event log (only entries relating to both callsigns:

2020-12-20 15:39:00 [info] - Now tracking flightplan data for EZY296
2020-12-20 16:47:09 [info] - Now tracking flightplan data for EZY978
2020-12-20 16:49:35 [info] - Set initial altitude for EZY978 (EGGD, BCN1X)
2020-12-20 16:49:36 [info] - API allocated general squawk 0477 to EZY978
2020-12-20 16:49:37 [info] - Assigned squawk 0477 to EZY978
2020-12-20 16:53:13 [info] - Stand id 248 assigned to EZY296
2020-12-20 17:14:30 [info] - Stand id 269 assigned to EZY296
2020-12-20 17:33:35 [info] - Set initial altitude for EZY978 (EGGD, BCN1X)
2020-12-20 17:33:35 [info] - Found existing API squawk allocation of 0477 for EZY978
2020-12-20 17:33:37 [info] - Assigned squawk 0477 to EZY978
2020-12-20 17:38:11 [info] - Stored flightplan for EZY296 has timed out

**Comment by AndyTWF** [comment]
Hi Trevor, thanks for the report will have a look at the data tomorrow and see what I can find out!

**Comment by AndyTWF** [comment]
Hi @trevorhannant I've had a look at it but can't find any obvious cause... Something like this is best debugged in-the-moment so I can pull all the network data. If you see it happening again can you let me know and I'll source the live feed data to determine why :)

**Comment by AndyTWF** [comment]
Hi Trevor - another update on this. We've not seen this happening again since, but we've increased the "range" at which an aircraft is deemed to be on a stand, as it was a bit too small causing valid occupancies to not be detected, which may have been the case here!

**Comment by trevorhannant** [comment]
Thanks Andy.

Question - is there a preference order for how stands get allocated or is it random?   Had one allocated 26S yesterday when that would be one of the last to be allocated over there as it effectively blocks 2 stands (26 and 28)?

**Comment by AndyTWF** [comment]
Hi Trevor - let's call it logically random!

It tries some really specific rules - e,g, Cargo flights, specific airlines / destinations etc. It then has a list of "general use" stands that it'll try next, these are what you could call "desirable" stands, not remote etc. Then if all else fails it just gives anything that's free. 

Within any specific rule, it'll prefer stands that are closest to the aircrafts size/weight category, but after that it picks randomly so as to avoid just going "1, 2, 3, 4" etc.

I can see that 26S is marked as a desirable stand. If you can give me a list of stands at Bristol that would say should be lower in the pile, I'll mark them as such so that they don't get used until last!

**Comment by trevorhannant** [comment]
Can things be removed from auto-allocation but still be manually selectable?   If so, could you remove the following from auto-allocation:

- E/W Stands
- 26S
- 38-39
- 7N

...as these are effectively "last flight of the day" stands where they'd also be first out as they block a significant number of other "regular use" stands.  But having them selectable by the controller should something "oversize" come in would be handy.

As far as a lower priority:

- 3R (only for 757 if 2 occupied)
- 19/20

**Comment by AndyTWF** [comment]
Hi Trevor, thanks for the info - do you include W8E, W9E, 7, 12 for example in the E/W stands?

**Comment by trevorhannant** [comment]
Those are OK

**Comment by AndyTWF** [comment]
Hi Trevor - these stands have been removed from auto assignment. Have you seen the behaviour described in the issue since or am I ok to close this for now?

**Comment by trevorhannant** [comment]
Looked good last night but wasn't hugely busy.  Will re-open if I spot it happening on a busier session later...
