### ISSUE TITLE
Separate countdown plugin

### ISSUE THREAD

**Issue by mjpikat** [VATSIM-UK/uk-controller-plugin#188]
Would it be possible for you to create countdown timer as a separate plugin? Thanks

**Comment by mjpikat** [comment]
Not replied, I guess you are not interested

**Comment by CalumTowers** [comment]
> Not replied, I guess you are not interested

Sorry that we missed this @mjpikat.

Our main focus right now is on creating great solutions for members of VATSIM UK. The generous licences that we apply to all of our open source code should allow anyone to extract fragments of functionality that they wish (for example, the countdown component).
