### ISSUE TITLE
Screen Resize Puts Displays Off Screen

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/uk-controller-plugin#21]
- Resizing the screen or simply going from a large monitor to a laptop display means things go off screen.

**Comment by hsugden** [comment]
I believe (though this may be a false memory) that in one plugin I once used, that there was a simple command line function to just reset the positions to 0,0 - perhaps the easiest solution?

**Comment by AndyTWF** [comment]
Done
