### ISSUE TITLE
Brussels intention code enhancements

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-plugin#211]
https://github.com/VATSIM-UK/uk-controller-plugin/blob/main/src/intention/BrusselsAirfieldGroup.cpp

Have got some new information regarding intention codes for Brussels arrivals.

**EB** = EBBR EBMB EBCI EBCV EBAW EBLG

New code **EX** = EBKT EBOS

**Comment by AndyTWF** [comment]
Hi @hsugden, can you confirm whether the rule of "must be routing via KOK" still applies?

**Comment by hsugden** [comment]
Sorry yes, should’ve specified. All should be via KOK
