### ISSUE TITLE
Hold manager - adjacent holds overlapping

### ISSUE THREAD

**Issue by cbyworth** [VATSIM-UK/uk-controller-plugin#222]
The hold manager very helpfully inserts conflicting aircraft into the vertical stack list to help controllers identify conflicts.

The issue is aircraft holding in adjacent holds (witnessed at Gatwick with TIMBA/WILLO) which are deemed separated appear in each others lists. During MWM etc the frequency with which this happens makes using the VSL less effective.

Aircraft that remain within the hold protected areas shouldn't appear in the other stack's list. To simplify for us, we could remove any overlap with a straight line where the X nm ranges of two holds' VSL conflicting traffic zone overlap.

Hopefully simpler with this terrible picture:
![Screenshot_20210205-225908](https://user-images.githubusercontent.com/45854780/107098386-fc7bdb00-6806-11eb-9767-1d924ca065a8.png)

Where the TIMBA/WILLO hold regions overlap amend with a straight line that form a boundary between the two hold regions.

**Comment by AndyTWF** [comment]
Chatted - easier way to do this:

- For non-holding traffic, keep the 10 (or whatever it is) mile buffer and warn if they enter at a conflicting level
- For two aircraft that are assigned to a hold, default it to the 10(ish) miles, but allow "deemed separation" between holds at certain levels
