### ISSUE TITLE
History trail large(?) maximum doesn't save

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-plugin#24]
When changing the history trail length to say, 99, saving the settings (and hence closing the history trail setting dialog) enacts such a command. i.e. there will be 99 blip trails

However, when opening the history trail dialog again, the previously saved length does not save - this doesn't seem to occur for lower value numbers

**Comment by AndyTWF** [comment]
The history trail length is capped at 50 (hence why it doesnt save above this!) - we can increase this if you think it would be useful :)

**Comment by hsugden** [comment]
Ah yes, looks I failed reply to this - I liked the 99 maximum in VCA, mainly for self indulgence/reflection at a good looking vectoring pattern! Either way, even when someone sets a value above the maximum, I think it would make sense to set the number in the dialog to that maximum.

**Comment by AndyTWF** [comment]
Okies, I'll add it to the todo list :)
