### ISSUE TITLE
UKCP to set the intention code as an annotation to the flightplan  

### ISSUE THREAD

**Issue by GeorgeBarlow** [VATSIM-UK/uk-controller-plugin#240]
Could we include this, so other plugins can utilise intention codes generated by UKCP? Currently having to generate it twice, this would be a huge benefit!

**Comment by AndyTWF** [comment]
Hi @GeorgeBarlow, thanks for the suggestion!

This is something that we can do however I’m conscious that a lot of other popular plugins use the flight strip annotations and we’re getting more and more requests for various bits of data to the point that we soon won’t have any place to put it!

For that reason, I’m currently thinking about solutions that allows UKCP to share its data with plugins en-masse. It’s likely to be something like message passing on the Win32 API, so for example, UKCP sets a new intention code then sends all concerned plugins a message along the lines of “I just set code D1 for BAW459”.

It shouldn’t be too much work on your part to integrate with something along these lines - it’s well documented and I can give you code samples from the AFV Bridge plugin to help. Will let you know when I’ve worked out how to achieve it so you can feed back on it :)

**Comment by AndyTWF** [comment]
Hi @GeorgeBarlow, just an update.

We're currently working with the vStrips team to develop a communication protocol between the two applications for the purpose of sharing data and allowing vStrips to perform actions in the plugin. This will be designed in a way that will allow other plugins to receive the same data.

It won't be something we can do through annotations for the reasons shared above, but hopefully will be done in a way that's well documented and easy to implement for other plugins who want to subscribe to UKCP data!

Will let you know more as we have it 🌮

**Comment by AndyTWF** [comment]
Hi @GeorgeBarlow, this functionality is now available via our new integration framework. You can find the docs for interacting with us here: https://vatsim-uk.github.io/uk-controller-plugin/IntegrationGuide/IntegrationGuide.html

If you have any questions / require assistance with this, please open up another issue :)
