### ISSUE TITLE
Make 'next frequency' accessible to other plugins

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-plugin#241]
In the same way that UKCP makes the 'UKCP Stand' accessible to vStrips, could the 'next frequency' - as determined by UKCP and the API - be made readable to other plugins?

**Comment by AndyTWF** [comment]
Relates to #240 as we’ll probably bring these under the same umbrella for a solution.

**Comment by AndyTWF** [comment]
Hi @hsugden,

Looking at this, do you expect that in the future a wider range of data may be required by vStrips? The way we share data with vSMR (and vStrips) is that we use the flight strip annotations in EuroScope. This solution will only be able to serve us for a limited time however, as TopSky uses 5 or 6 of the annotations (of 9), so eventually we'll run out.

I've been thinking about possible ways forward and my thoughts are that we should probably implement an event broadcasting system in UKCP.

So for example:

1. Next frequency is updated by UKCP.
2. UKCP broadcasts some  event on the users machine to other interested parties.
3. Other interested parties can consume the event data to display what they need to.

It would follow that in reverse, third parties could ping UKCP with requests for what data they'd like / action they'd like it to perform and then UKCP could respond in some way.

Given previous experience / simplicity, my thought right now is that we could utilise the "Hidden Window" method of message passing on the users machine, this has the advantage of low overhead and comprehensive documentation.

So in this instance, vStrips would have a window that could receive Windows messages. UKCP would broadcast the next frequency to it whenever it changes.

Any thoughts welcome!

**Comment by AndyTWF** [comment]
Hi @hsugden - the integration framework required to make this happen is now released, I've communicated this with Matt and the team over at vStrips!
