### ISSUE TITLE
Prenote and release messages in chat area

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/uk-controller-plugin#410]
Allow this so people with the window closed know when one comes in.

**Comment by hsugden** [comment]
@AndyTWF resolved, no? I'm pretty sure I got one of these the other day! 😄 (very useful it was)

**Comment by AndyTWF** [comment]
Not resolved yet - I don't think! We let you know of "suggested" prenotes, but we don't do "you've received an active prenote request from someone else". I'll be looking at this one shortly!
