### ISSUE TITLE
EDT display

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-plugin#42]
When there is no EDT, could it display nothing rather than 00:00? 😄 

http://prntscr.com/n0n6q0

**Comment by AndyTWF** [comment]
Hi Harry - I've had a look at this, UKCP doesn't use 00:00 unless they actually specify midnight. UKCP's default is "--:--" :)

**Comment by hsugden** [comment]
Fairs, could it display though please? This fits the fact that 'Slot' and other non-UKCP fields are blank when there is no data to display.

**Comment by AndyTWF** [comment]
Sure - will look into it :) Or I could make it configurable?

**Comment by AndyTWF** [comment]
Done
