### ISSUE TITLE
Large gap behind aircraft before history dots

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/uk-controller-plugin#436]
This appears to be a more recent thing, but aircraft end up having a large gap behind them before the history dots start. This didn't used to be the case (could be velocity related?). Have a play, see what we can come up with.

https://github.com/VATSIM-UK/uk-controller-plugin/blob/1e57ab1f667265170ae9de546f66493b765ecbf6/src/plugin/historytrail/HistoryTrailRenderer.cpp#L350

**Comment by hsugden** [comment]
Ah yes, fading on:

![image](https://user-images.githubusercontent.com/12017284/155998442-19cefadd-3dd8-4b5b-9492-ff07b50bba32.png)

Fading off:

![image](https://user-images.githubusercontent.com/12017284/155998453-a651d3c2-3ff5-4109-9257-f0e05ef219ce.png)

**Comment by AndyTWF** [comment]
Interesting you mention fading… I think I may have just worked out the issue… Will work on a fix :)
