### ISSUE TITLE
C-mode & departure list

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-plugin#46]
I switched from Easy VATSIM to C-mode correlation, and the EOBT/EDT/AOBT all disappeared!

**Comment by AndyTWF** [comment]
Just to clarify - which list have they disappeared from? The departure list?

**Comment by hsugden** [comment]
Yes, departure list :)

Easy:

![Screenshot_1](https://user-images.githubusercontent.com/12017284/56469243-d9fcb000-642e-11e9-9c00-a8288e3c4286.png)

C-mode:

![Screenshot_2](https://user-images.githubusercontent.com/12017284/56469244-dd903700-642e-11e9-861a-1ab34766cc0f.png)

**Comment by AndyTWF** [comment]
Thanks, will look!

**Comment by AndyTWF** [comment]
Done in #51
