### ISSUE TITLE
Heathrow CPT Squawks Not Assigning

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/uk-controller-plugin#48]
Heathrow CPT departures aren't having squawks assigned. This is because ES tells the plugin that the aircraft are too far from origin. Find a way to increase the allowable distance to allow this to work.

**Comment by artturnip** [comment]
We're also looking at this on the sector file end. We're planning to add an extra waypoint on the CPT easterly SIDs. I've tried the proposed fix out with the current version of UKCP and it seems to work, but could you take a look at the SID routes below and suggest whether this fix might work or not?

## Current
![image](https://user-images.githubusercontent.com/2829581/57484432-ed1dd580-72a0-11e9-97d7-ab85add47927.png)

## Proposed
![image](https://user-images.githubusercontent.com/2829581/57484446-f1e28980-72a0-11e9-89df-589bef815c87.png)

**Comment by AndyTWF** [comment]
@artturnip That will work great :)

**Comment by AndyTWF** [comment]
Done in #49
