### ISSUE TITLE
Revised Fx intention codes (AIRAC 2212)

### ISSUE THREAD

**Issue by hazzas-99** [VATSIM-UK/uk-controller-plugin#498]
**Effective 01 December 2022**

With the introduction of new COP RENEQ between ScAC Humber and MUAC Jever sector, the Fx intention codes are revised:

Maastricht
F4 - RENEQ
F3 - LONAM
F2 - TOPPA
F1 - GODOS

F   - LAMSO

**Comment by AndyTWF** [comment]
Read to go @hsugden https://github.com/VATSIM-UK/uk-controller-plugin/pull/500
