### ISSUE TITLE
Missing Scottish intention codes

### ISSUE THREAD

**Issue by hazzas-99** [VATSIM-UK/uk-controller-plugin#503]
Southbound traffic via NIMAT departing EGPH would expect to display intention code G5 - none shown.

Traffic via MOLAK, NIPIT, ERNAN, DEGOS, ROTEV and NIMAT could all theoretically route southwest/south.

**Comment by AndyTWF** [comment]
Just to confirm @hazzas-99 what position were you on at the time?
