### ISSUE TITLE
Scottish Upper intention codes display to LON_N

### ISSUE THREAD

**Issue by hazzas-99** [VATSIM-UK/uk-controller-plugin#517]
Intention code E9 (BELOX) displaying to LON_N_CTR - should only display to Scottish positions, as LAMSO (F) is the UK exit code

![image](https://user-images.githubusercontent.com/12017284/232291106-ac8a0d30-da3f-450e-9320-b5b178bc6822.png)

Route string: `RATPK3 FRNCK DCT MLF J107 DDY DCT TIMMR/N0478F350 DCT HML DCT 54N090W 57N080W 59N070W DCT RODBO/M083F350 DCT MAXAR DCT 62N050W/M083F370 62N040W 61N030W 59N020W DCT AGORI/N0476F370 DCT MIMKU DCT BELOX/N0471F390 L603 LAMSO DCT EDUPO Z739 MISGO/N0450F230 T911 ROLIS ROLIS3D`

**Comment by AndyTWF** [comment]
Have had a look into this - looks like the API had some extra BELOX's from the original data import, but without the conditions of it being SCO. Have removed these which should fix it!
