### ISSUE TITLE
failed to create file UK\Data\Sector\UK_2023_06.7zip

### ISSUE THREAD

**Issue by kpx1894** [VATSIM-UK/uk-controller-plugin#528]
Hi,

I keep getting this error message in Euroscope: "failed to create file UK\Data\Sector\UK_2023_06.7zip" - is it related to UK plugin?

BR,
K.

**Comment by AndyTWF** [comment]
Hi @kpx1894!

Apollogies for the delay - I've been away :)

This is an issue with EuroScope itself trying to automatically update the sector file, not to do with the UK plugin.
