### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by caspianmerlin** [VATSIM-UK/uk-controller-plugin#538]
Two Windows dialog boxes informing me of a UKCP unhandled exception popped up ~10 mins into controlling session, followed by the plugin unloading. Multiple people appeared to experience this at the same time. Something to do with ECFMP perhaps? Logfile attached.
[plugin-20230916201916.txt](https://github.com/VATSIM-UK/uk-controller-plugin/files/12641482/plugin-20230916201916.txt)

**Comment by AndyTWF** [comment]
Thanks for the report! I’ll have a look into it!

**Comment by AndyTWF** [comment]
Hi @caspianmerlin sorry for the delay this was quite hard to track down. I believe I've identified the issue and am currently preparing a fix :)
