### ISSUE TITLE
Unhandled exception - Failed to accept integration server connection: 10004

### ISSUE THREAD

**Issue by caspianmerlin** [VATSIM-UK/uk-controller-plugin#549]
Win32 dialog box saying unhandled exception within UKCP. Logfile attached, seems to be 'Failed to accept integration server connection: 10004' that's the issue.
[plugin-20231209195320.txt](https://github.com/VATSIM-UK/uk-controller-plugin/files/13625632/plugin-20231209195320.txt)

**Comment by caspianmerlin** [comment]
Initial crash was when pluign had been running for an hour or so, but it now crashes instantly on load with the same error.

**Comment by AndyTWF** [comment]
Hi @caspianmerlin - the websocket log is a bit of a red herring, I should probably tidy that up!

I'm going to put some logging into the plugin to try and ascertain where the exception is coming from, will let you know!

**Comment by caspianmerlin** [comment]
Ah makes sense! I see you've added the extra logging, if I have any further crashes I'll put the logs here.
