### ISSUE TITLE
'Stacked' Aircraft In Hold Manager

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-plugin#78]
Excuse the pun! Aircraft appear to be able to stack up on top of each other in the hold manager if at the same level. Whilst this is really a controller's problem, is there a way to keep an aircraft in the level above or add a new line with a red warning box etc.? Just something to make it more obvious that something has gone awry 😄

**Comment by cbyworth** [comment]
Afraid I have no ability to code this but if anybody who can wanted some inspiration for how this could work this might be of use from how the NATS VSL works
![VSL](https://user-images.githubusercontent.com/45854780/68995904-daf1a500-088a-11ea-8b19-b3bdf934b489.jpg)

**Comment by AndyTWF** [comment]
Thanks for the info :)

**Comment by AndyTWF** [comment]
Hi @hsugden @cbyworth, just to let you know that aircraft at the same level has been implemented in the new version of the hold display and will display the green bounding box around aircraft at the same level :)
