### ISSUE TITLE
Aircraft Not Removed From Hold Manager On Disconnect

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-plugin#80]
Don't have many details on this, except that this aircraft in the screenshot disconnected and still hadn't disappeared after 30 seconds or so.

![image](https://user-images.githubusercontent.com/12017284/66777315-a02dd300-eec0-11e9-9697-0e6e45876029.png)

**Comment by AndyTWF** [comment]
Thanks for the report - this will probably be because we do some checks against the FP that don't pass during a disconnect. Will fix on the next release :)
